# Generated by Django 4.0.2 on 2022-02-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content_type',
            new_name='content',
        ),
    ]
