# Generated by Django 4.0.2 on 2022-02-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_content_type_note_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('title',)},
        ),
    ]
